#!/usr/bin/env python3
"""Claude ST's icon, drawn as 32x32 1-bit pixel art: an SM124-style
monochrome monitor whose dark screen shows an eight-ray spark (a plain
pixel asterisk) and a GEM
command prompt. Writes:
  st/icon.h        the bitmap for CLAUDE.PRG (16-bit words, MSB first)
  docs/icon.png    an enlarged preview
  st/CLAUDE.ICN    the icon in the classic ICN text format, for icon editors
"""
import os

W = H = 32
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
px = [[0] * W for _ in range(H)]


def put(x, y, v=1):
    if 0 <= x < W and 0 <= y < H:
        px[y][x] = v


def rect(x0, y0, x1, y1, v=1):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            put(x, y, v)


def hline(x0, x1, y, v=1):
    rect(x0, y, x1, y, v)


def vline(x, y0, y1, v=1):
    rect(x, y0, x, y1, v)


# --- monitor case: a rounded box with a thicker bottom bezel ---
hline(3, 28, 0)
hline(2, 29, 1)
vline(1, 2, 21)
vline(30, 2, 21)
put(2, 1); put(29, 1)
hline(2, 29, 22)
hline(3, 28, 23)
put(2, 21); put(29, 21)
# bezel shading on the right/bottom for a little depth
vline(29, 3, 21)
hline(3, 28, 21)

# --- screen: dark CRT with rounded corners ---
rect(4, 3, 27, 18)
for x, y in [(4, 3), (27, 3), (4, 18), (27, 18)]:
    put(x, y, 0)

# --- the spark: eight rays from a hollow centre, in "white" ---
cx, cy = 11, 10
for r in range(0, 6):
    put(cx + r, cy, 0); put(cx - r, cy, 0)
    put(cx, cy + r, 0); put(cx, cy - r, 0)
for r in range(1, 5):
    put(cx + r, cy + r, 0); put(cx - r, cy - r, 0)
    put(cx + r, cy - r, 0); put(cx - r, cy + r, 0)
# a slightly heavier core so it reads as one shape at 1:1
for dx, dy in [(1, 0), (-1, 0), (0, 1), (0, -1)]:
    put(cx + dx, cy + dy, 0)

# --- GEM-style prompt on the right of the screen: ">" and a block cursor ---
for i in range(3):
    put(18 + i, 13 + i, 0)
    put(18 + i, 17 - i, 0)
rect(22, 15, 24, 16, 0)

# --- power LED on the bezel, like the SM124's ---
rect(25, 21, 26, 21, 0)
put(25, 21, 1)

# --- neck and tilting foot ---
rect(13, 24, 18, 25)
hline(8, 23, 26)
hline(7, 24, 27)
vline(6, 28, 29); vline(25, 28, 29)
hline(7, 24, 28, 0)
hline(6, 25, 30)
hline(7, 24, 29)
put(7, 28); put(24, 28)
hline(8, 23, 31, 0)

words = []
for y in range(H):
    for half in range(2):
        v = 0
        for b in range(16):
            v = (v << 1) | px[y][half * 16 + b]
        words.append(v)

with open(os.path.join(ROOT, "st", "icon.h"), "w") as f:
    f.write("/* Claude ST icon, 32x32 1-bit, generated by tools/icon/make_icon.py */\n")
    f.write("#define ICON_W 32\n#define ICON_H 32\n")
    f.write("static const unsigned short icon_bits[ICON_H * 2] = {\n")
    for y in range(H):
        f.write("\t0x%04x, 0x%04x,\n" % (words[2 * y], words[2 * y + 1]))
    f.write("};\n")

with open(os.path.join(ROOT, "st", "CLAUDE.ICN"), "w", newline="\r\n") as f:
    f.write("/* GEM Icon Definition: */\n#define ICON_W 0x0020\n#define ICON_H 0x0020\n")
    f.write("#define DATASIZE 0x0040\nUWORD image[DATASIZE] =\n{ ")
    f.write(",\n  ".join(", ".join("0x%04X" % w for w in words[i:i + 8])
                         for i in range(0, len(words), 8)))
    f.write("\n};\n")

try:
    from PIL import Image
    img = Image.new("RGB", (W, H), "white")
    for y in range(H):
        for x in range(W):
            if px[y][x]:
                img.putpixel((x, y), (0, 0, 0))
    img.resize((W * 8, H * 8), Image.NEAREST).save(os.path.join(ROOT, "docs", "icon.png"))
except ImportError:
    pass

for y in range(H):
    print("".join("#" if v else "." for v in px[y]))
